### ISSUE TITLE
Lab 10  - blocked by CORS policy

### ISSUE THREAD

**Issue by 274188A** [scolapicchioni/blazor#5]
Hi,
I'm hitting a CORS policy error (even running the Solution project) - when tying to navigate to upload photo from main menu

> Access to XMLHttpRequest at 'https://localhost:5031/.well-known/openid-configuration' from origin 'https://localhost:5001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by scolapicchioni** [comment]
Did you delete the IdentityServer DataBase and then run the command
`dotnet run /seed`
to rebuild the IdentityServer database?

**Comment by 274188A** [comment]
yip forgot about that...thanks! :-)
